agent: COCOStuffF1Trainer 

# TODO: Update this path to your dataset folder
dataset path: D:\code\data\filtered_datasets\stuff_small_toy
img height: 106
img width: 160

model: deep_lab_f1
learning rate: 0.01

# TODO: Update this batch size to fill GPUs
batch size: 16

n_outer: 80
n_inner: 800

# Grid Search Parameters
beta: 0.001
threshold: 0.05

# Primal update parameter
eta_tau: 0.01
eta_eps: 0.01
eta_w: 0.01

# Dual update parameters
eta_gamma: 0.001
eta_lamb: 0.001
eta_mu: 0.00001
