agent: COCOStuffTestDev2017Evaluator
dataset path: /home/ubuntu/data/cocostuff/evaluation
model: deep_lab_f1
checkpoint path: /home/ubuntu/code/src/f1-cv/experiments/coco_stuff_f1_deep_lab_amazon/checkpoints/9.ckpt