agent: MNISTF1Trainer
dataset path: /home/abhay/data/mnistf1
learning rate: 0.01
batch size: 100
n_outer: 20
n_inner: 2400
model: FFNetF1

# Normalization coefficient
beta: 0.1

# Primal update parameter
eta_tau: 0.01
eta_eps: 0.01
eta_w: 0.01

# Dual update parameters
eta_gamma: 0.001
eta_lamb: 0.001
eta_mu: 0.00001
