agent: COCOStuffF1Trainer 
dataset path: /home/abhay/data/filtered_datasets/stuff_small_clique
model: deep_lab_f1
learning rate: 0.01
batch size: 144
n_outer: 80
n_inner: 800

# Normalization coefficient
beta: 0.001

# Primal update parameter
eta_tau: 0.01
eta_eps: 0.01
eta_w: 0.01

# Dual update parameters
eta_gamma: 0.001
eta_lamb: 0.001
eta_mu: 0.00001
