agent: COCOStuffF1Trainer 
dataset path: D:\code\data\filtered_datasets\stuff_small
model: seg_net_f1
learning rate: 0.01
batch size: 3
n_outer: 80
n_inner: 36000

# Normalization coefficient
beta: 0.001

# Primal update parameter
eta_tau: 0.01
eta_eps: 0.01
eta_w: 0.01

# Dual update parameters
eta_gamma: 0.001
eta_lamb: 0.001
eta_mu: 0.00001
