agent: COCOStuffValidator
dataset path: /home/abhay/data/cocostuff/dataset/images/val2017
model: deep_lab_f1
checkpoint path: /home/abhay/code/src/f1-cv/experiments/archive/coco_stuff/coco_stuff_full/coco_stuff_f1_deep_lab_amazon/checkpoints/9.ckpt


# Divide the evaluation set into 5 pieces 
eval split divisor: 5
# This is the 0th piece
split number: 3
