agent: COCOStuffTrainer

# Dataset
dataset path: /home/abhay/code/data/filtered_datasets/stuff_2018_fixed
is cropped: true
crop width: 321
crop height: 321
in memory: false

# Model
model: deep_lab

# Training hyperparameters 
epochs: 50
learning rate: 0.01
batch size: 16
