agent: COCOStuffBaselineTrainer
epochs: 100
dataset path: /home/abhay/data/filtered_datasets/stuff_clique
learning rate: 0.01
batch size: 8
checkpoint path: experiments/coco_stuff_baseline_clique/checkpoints/3.ckpt
