agent: MNISTF1Trainer
epochs: 10
dataset path: D:\code\data\filtered_datasets\mnistf1
learning rate: 0.01
batch size: 100
n_outer: 4
n_inner: 1200

# Normalization coefficient
beta: 0.001

# Primal update parameter
eta_tau: 0.01
eta_eps: 0.01
eta_w: 0.01

# Dual update parameters
eta_gamma: 0.1
eta_lamb: 0.1
eta_mu: 0.00001
