agent: MNISTBSTrainer
dataset path: /home/abhay/data/mnistf1
learning rate: 0.001
batch size: 100
epochs: 80
model: FFNet
checkpoint path: D:\code\src\f1-cv\experiments\mnist_ffnet_baseline\checkpoints\50.ckpt